const BTEC_UNITS = [
  { number: 1, title: "Engineering Principles", imageQuery: "engineering,workshop" },
  { number: 2, title: "Delivery of Engineering Processes Safely as a Team", imageQuery: "engineering,safety" },
  { number: 3, title: "Engineering Product Design and Manufacture", imageQuery: "product design,engineering" },
  { number: 4, title: "Applied Commercial and Quality Principles in Engineering", imageQuery: "quality control,factory" },
  { number: 5, title: "Principles and Applications of Mechatronics", imageQuery: "mechatronics,robotics" },
  { number: 6, title: "Design and Manufacture in Engineering", imageQuery: "cad,manufacturing" },
  { number: 7, title: "Calculus to Solve Engineering Problems", imageQuery: "mathematics,engineering" },
  { number: 8, title: "Electrical and Electronic Principles", imageQuery: "electronics,circuit board" },
  { number: 9, title: "Computer Aided Design in Engineering", imageQuery: "cad computer,engineering" },
  { number: 10, title: "Mechanical Behaviour of Engineering Materials", imageQuery: "materials testing,metal" },
  { number: 11, title: "Modern Manufacturing Systems", imageQuery: "factory automation" },
  { number: 12, title: "Mechanical Measurement and Inspection Technologies", imageQuery: "metrology,inspection" },
  { number: 13, title: "Mechanical Testing of Materials", imageQuery: "testing machine,materials" },
  { number: 14, title: "Applications of Computer Numerical Control in Engineering", imageQuery: "cnc machine" },
  { number: 15, title: "Electrical Systems and Fault Finding", imageQuery: "electrical maintenance" },
  { number: 16, title: "Microcontroller Systems for Engineers", imageQuery: "microcontroller,arduino" },
  { number: 17, title: "Secondary Machining Techniques", imageQuery: "metal machining" },
  { number: 18, title: "Mechanical Principles and Applications", imageQuery: "mechanical engineering" },
  { number: 19, title: "Hydraulics and Pneumatics", imageQuery: "hydraulics,pneumatics" },
  { number: 20, title: "Investigating the Properties and Processing of Engineering Materials", imageQuery: "engineering materials" },
  { number: 21, title: "Computer Aided Manufacture in Engineering", imageQuery: "cam software,manufacturing" },
  { number: 22, title: "Electronic Devices and Circuits", imageQuery: "electronic components" },
  { number: 23, title: "Electrical Machines", imageQuery: "electric motor" },
  { number: 24, title: "Electronic Measurement and Testing", imageQuery: "oscilloscope,electronics" },
  { number: 25, title: "Properties and Applications of Engineering Materials", imageQuery: "steel,alloy,materials" },
  { number: 26, title: "Further Mechanical Principles and Applications", imageQuery: "machine parts" },
  { number: 27, title: "Further Electrical and Electronic Principles", imageQuery: "advanced electronics" },
  { number: 28, title: "Further Mathematics for Engineering Technicians", imageQuery: "equations,math" },
  { number: 29, title: "Work Experience in Engineering", imageQuery: "engineering apprentice" },
  { number: 30, title: "Computer Programming and Databases", imageQuery: "coding,computer" },
  { number: 31, title: "Electrical Machines and Drives", imageQuery: "motor drive,inverter" },
  { number: 32, title: "Thermodynamic Principles and Practice", imageQuery: "heat,thermal" },
  { number: 33, title: "Industrial Systems", imageQuery: "industrial plant" },
  { number: 34, title: "Industrial Process Controllers", imageQuery: "control panel,automation" },
  { number: 35, title: "Fluid Mechanics", imageQuery: "fluid flow,engineering" },
  { number: 36, title: "Programmable Logic Controllers", imageQuery: "plc,automation" }
].map((u) => ({
  ...u,
  code: `Unit ${u.number}`,
  image: `https://source.unsplash.com/1200x800/?${encodeURIComponent(u.imageQuery)}`
}));
